### PR TITLE
Update otel collector contrib to v0.105.0

### PR DESCRIPTION
**Pull request by damemi**

### CODE REVIEW

**Comment by damemi** [comment]
@ridwanmsharif should we also push a git tag to the repo for manifests v0.1.0?

**Review by ridwanmsharif — APPROVED** [review]

**Comment by ridwanmsharif** [comment]
> should we also push a git tag to the repo for manifests v0.1.0?

Yup, once this lands - lets push a git tag

**Comment by damemi** [comment]
> > should we also push a git tag to the repo for manifests v0.1.0?
> 
> Yup, once this lands - lets push a git tag

Done - https://github.com/GoogleCloudPlatform/otlp-k8s-ingest/tree/v0.1.0

**Comment by damemi** [comment]
Also created a release 🎉 https://github.com/GoogleCloudPlatform/otlp-k8s-ingest/releases/tag/v0.1.0

**Pull request merged**
